/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MoviesType } from "./components/movies-component/movies-component";
export namespace Components {
    interface MoviesComponent {
        "movies": MoviesType;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLMoviesComponentElement extends Components.MoviesComponent, HTMLStencilElement {
    }
    var HTMLMoviesComponentElement: {
        prototype: HTMLMoviesComponentElement;
        new (): HTMLMoviesComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "movies-component": HTMLMoviesComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MoviesComponent {
        "movies"?: MoviesType;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "movies-component": MoviesComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "movies-component": LocalJSX.MoviesComponent & JSXBase.HTMLAttributes<HTMLMoviesComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
